// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's ID and email as authenticated by the MCP OAuth token.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({
            user_id: ctx.getUserId(),
            email: ctx.getUserEmail(),
            client_id: ctx.getClientId()
          })
        }
      ],
      structuredContent: {
        user_id: ctx.getUserId(),
        email: ctx.getUserEmail()
      }
    };
  }
});

// src/lib/mcp/tools/list-residents.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_residents_default = defineTool2({
  name: "list_residents",
  title: "List residents",
  description: "List residents visible to the signed-in user (RLS-scoped). Optionally filter by apartment or name substring.",
  inputSchema: {
    apartment: z.string().trim().optional().describe("Filter by exact apartment identifier."),
    search: z.string().trim().optional().describe("Case-insensitive substring match on the resident name."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ apartment, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("residents").select("id,name,apartment,block,phone,email,vehicle_plate").order("apartment", { ascending: true }).limit(limit ?? 25);
    if (apartment) q = q.eq("apartment", apartment);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { residents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-access-entries.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_access_entries_default = defineTool3({
  name: "list_access_entries",
  title: "List access entries",
  description: "List recent visitor/access entries visible to the signed-in user (RLS-scoped). Optionally filter by apartment.",
  inputSchema: {
    apartment: z2.string().trim().optional().describe("Filter by apartment."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ apartment, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb2(ctx).from("access_entries").select(
      "id,visitor_name,visitor_document,apartment,resident_name,entry_time,exit_time,visitor_type,vehicle_plate"
    ).order("entry_time", { ascending: false }).limit(limit ?? 25);
    if (apartment) q = q.eq("apartment", apartment);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-mails.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_mails_default = defineTool4({
  name: "list_mails",
  title: "List mail/correspondence",
  description: "List correspondence items visible to the signed-in user (RLS-scoped). Optionally filter by apartment or pickup status.",
  inputSchema: {
    apartment: z3.string().trim().optional(),
    picked_up: z3.boolean().optional().describe("If set, filter by pickup status."),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ apartment, picked_up, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb3(ctx).from("mails").select("id,apartment,resident_name,mail_type,description,received_at,picked_up,picked_up_at").order("received_at", { ascending: false }).limit(limit ?? 25);
    if (apartment) q = q.eq("apartment", apartment);
    if (typeof picked_up === "boolean") q = q.eq("picked_up", picked_up);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { mails: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-announcements.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_announcements_default = defineTool5({
  name: "list_announcements",
  title: "List announcements",
  description: "List condominium announcements visible to the signed-in user (RLS-scoped).",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("announcements").select("id,title,content,is_urgent,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { announcements: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kxdqffkkufgsizszchvw";
var mcp_default = defineMcp({
  name: "portalguard-mcp",
  title: "PortalGuard MCP",
  version: "0.1.0",
  instructions: "Ferramentas do PortalGuard (portaria de condom\xEDnio). Ap\xF3s conectar via OAuth, use `whoami` para confirmar a identidade. Ferramentas de leitura respeitam o RLS do usu\xE1rio autenticado: `list_residents`, `list_access_entries`, `list_mails`, `list_announcements`.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_residents_default,
    list_access_entries_default,
    list_mails_default,
    list_announcements_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
